version: "3.8"

services:
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    volumes:
     - ./webroot/conf.d:/etc/nginx/conf.d
     - ./webroot/log:/var/log/nginx
     - ./webroot/www/html:/var/www/html
     - ./letsencrypt:/etc/letsencrypt
    ports:
     - "443:443"
     - "80:80"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1/health"]
      interval: 5s
      retries: 3
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
  cert-manager:
    image: certbot/certbot
    container_name: cert-manager
    entrypoint: ["/bin/sh", "/usr/local/bin/certbot-script.sh"]
    environment:
      - DEBUG=true
    depends_on:
      webserver:
        condition: service_healthy
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./webroot/www/html:/var/www/html
      - ./certbot-script.sh:/usr/local/bin/certbot-script.sh